=== garrichello/gcoret/mod/calc/templates/ctdl.dtd
<!ELEMENT task (service, metadb, computing, (data|destination)+, processing+)>
<!ATTLIST task
    uid ID #REQUIRED
    owner CDATA #IMPLIED
    description CDATA #IMPLIED
    root_path CDATA #IMPLIED
    data_module_path CDATA #REQUIRED>


<!ELEMENT service (timePeriod)>
<!ATTLIST service
    processingClass CDATA #REQUIRED
    calculationParameter CDATA #REQUIRED
    trend CDATA #REQUIRED
    isBaseLayer CDATA #REQUIRED>
<!ELEMENT timePeriod (dateStart, dateEnd)>
<!ATTLIST timePeriod
    type CDATA #REQUIRED>
<!ELEMENT dateStart EMPTY>
<!ATTLIST dateStart
    year CDATA #REQUIRED
    month CDATA #REQUIRED
    day CDATA #REQUIRED>
<!ELEMENT dateEnd EMPTY>
<!ATTLIST dateEnd
    year CDATA #REQUIRED
    month CDATA #REQUIRED
    day CDATA #REQUIRED>


<!ELEMENT metadb EMPTY>
<!ATTLIST metadb
    host CDATA #REQUIRED
    name CDATA #REQUIRED
    user CDATA #REQUIRED
    password CDATA #REQUIRED>
<!ELEMENT computing EMPTY>
<!ATTLIST computing
    system CDATA #REQUIRED
    type (LOCAL|REMOTE) #REQUIRED
    ip CDATA #IMPLIED>
<!ELEMENT data (description?, dataset?, variable?, region?, levels?, time?, param*)>
<!ATTLIST data
    uid ID #REQUIRED
    type (dataset|array|datafile|parameter) #REQUIRED
    kind (map|stations|lines) #IMPLIED>
<!ELEMENT description EMPTY>
<!ATTLIST description
    title CDATA #REQUIRED
    name CDATA #REQUIRED
    units CDATA #REQUIRED
    units_sfx CDATA #IMPLIED
    source CDATA #IMPLIED>
<!ELEMENT dataset EMPTY>
<!ATTLIST dataset
    name CDATA #REQUIRED
    resolution CDATA #REQUIRED
    time_step CDATA #REQUIRED
    scenario CDATA #REQUIRED
    module_path CDATA #IMPLIED>
<!ELEMENT variable EMPTY>
<!ATTLIST variable
    name CDATA #REQUIRED
    tempk2c CDATA "no">
<!ELEMENT region ((point, point, point+)|(tile+))>
<!ATTLIST region
    units (degrees|pathrow) #REQUIRED
    lon0 CDATA "0">
<!ELEMENT point EMPTY>
<!ATTLIST point
    lon CDATA #REQUIRED
    lat CDATA #REQUIRED>
<!ELEMENT tile EMPTY>
<!ATTLIST tile
    path CDATA #REQUIRED
    row CDATA #REQUIRED>
<!ELEMENT levels EMPTY>
<!ATTLIST levels
    values CDATA #REQUIRED>
<!ELEMENT time (segment+)>
<!ATTLIST time
    uid CDATA #IMPLIED	
    template CDATA #FIXED "YYYYMMDDHH"
    step CDATA #IMPLIED>
<!ELEMENT segment EMPTY>
<!ATTLIST segment
    name CDATA #REQUIRED
    beginning CDATA #REQUIRED
    ending CDATA #REQUIRED>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    uid ID #REQUIRED
    type (integer|float|string|intarr|fltarr|strarr|binary) #REQUIRED>

<!ELEMENT destination (file, projection?, coastline?, rivers?, countries?, graphics?)>
<!ATTLIST destination
    uid ID #REQUIRED
    type (image|raw) #REQUIRED>
<!ELEMENT file EMPTY>
<!ATTLIST file
    name CDATA #REQUIRED
    type (eps|geotiff|shape|geotiff24|netcdf|bin|xml|png) #REQUIRED>
<!ELEMENT projection (p0lon?, p0lat?, rot?, limits)>
<!ATTLIST projection
    name CDATA #REQUIRED>
<!ELEMENT p0lon (#PCDATA)>
<!ATTLIST p0lon
    units CDATA #FIXED "degrees">
<!ELEMENT p0lat (#PCDATA)>
<!ATTLIST p0lat
    units CDATA #FIXED "degrees">
<!ELEMENT rot (#PCDATA)>
<!ATTLIST rot
    units CDATA #FIXED "degrees">
<!ELEMENT limits (limit, limit, limit, limit)>
<!ATTLIST limits
    units CDATA #FIXED "degrees">
<!ELEMENT limit (#PCDATA)>
<!ATTLIST limit
    role (left|right|top|bottom) #REQUIRED>
<!ELEMENT coastline EMPTY>
<!ATTLIST coastline
    visible (yes|no) #REQUIRED
    hires (yes|no) #REQUIRED>
<!ELEMENT rivers EMPTY>
<!ATTLIST rivers
    visible (yes|no) #REQUIRED
    hires (yes|no) #REQUIRED>
<!ELEMENT countries EMPTY>
<!ATTLIST countries
    visible (yes|no) #REQUIRED
    hires (yes|no) #REQUIRED>

<!ELEMENT graphics (width, height, axis?, lines?, legend?, colortable?, colorscale?, blackbg?, smoothing?, steps?)>
<!ATTLIST graphics
    title CDATA #REQUIRED
    kind (shaded|contour|station|tile|multiline|vector|regress2d) #REQUIRED>
<!ELEMENT width (#PCDATA)>
<!ATTLIST width
    units CDATA #FIXED "pixels">    
<!ELEMENT height (#PCDATA)>
<!ATTLIST height
    units CDATA #FIXED "pixels">    
<!ELEMENT axis (x, y, z?)>
<!ELEMENT x EMPTY>
<!ATTLIST x
    name CDATA #REQUIRED
    units CDATA #REQUIRED
    scale CDATA #IMPLIED
    visible CDATA "yes">
<!ELEMENT y EMPTY>
<!ATTLIST y
    name CDATA #REQUIRED
    units CDATA #REQUIRED
    scale CDATA #IMPLIED
    visible CDATA "yes">
<!ELEMENT z EMPTY>
<!ATTLIST z
    name CDATA #REQUIRED
    units CDATA #REQUIRED
    scale CDATA #IMPLIED
    visible CDATA "yes">
<!ELEMENT lines (line*)>
<!ELEMENT line EMPTY>
<!ATTLIST line
    name CDATA #REQUIRED
    style (solid|dotted|dashed) #REQUIRED
    symbol (none|plus|asterisk|period|diamond|triangle|square|X) #REQUIRED
    color CDATA #REQUIRED
    thick CDATA #REQUIRED
    visible CDATA #REQUIRED>
<!ELEMENT legend (units?, nlabels?, ncolors?, limited?, minimum?, maximum?, file?)>
<!ATTLIST legend
    title CDATA #REQUIRED
    kind (embedded|file|none) #REQUIRED
    type (continuous|discrete) #REQUIRED
    position (right|left|top|bottom|none) #REQUIRED>
<!ELEMENT units (#PCDATA)>
<!ELEMENT ncolors (#PCDATA)>
<!ELEMENT nlabels (#PCDATA)>
<!ELEMENT limited (#PCDATA)>
<!ELEMENT minimum (#PCDATA)>
<!ELEMENT maximum (#PCDATA)>
<!ELEMENT colortable (#PCDATA)>
<!ELEMENT colorscale (#PCDATA)>
<!ELEMENT blackbg (#PCDATA)>
<!ELEMENT smoothing (#PCDATA)>
<!ELEMENT steps (#PCDATA)>

<!ELEMENT processing (input+, output*)>
<!ATTLIST processing
    uid ID #REQUIRED
    class CDATA #REQUIRED
    module_path CDATA #IMPLIED>
<!ELEMENT input EMPTY>
<!ATTLIST input
    uid ID #REQUIRED
    data CDATA #REQUIRED>
<!ELEMENT output EMPTY>
<!ATTLIST output
    uid ID #REQUIRED
    data CDATA #REQUIRED>

=== garrichello/gcoret/mod/calc/templates/CalcMaxMax.tmpl.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE task SYSTEM "ctdl.dtd">
<task uid='Task1' owner='Owner1' description='' root_path='/opt/gcoret/' data_module_path=''>
    <service processingClass='' calculationParameter='' trend='' isBaseLayer=''><!-- GUI service params -->
      <timePeriod type=''>
        <dateStart year='' month='' day=''/>
        <dateEnd year='' month='' day=''/>
      </timePeriod>
    </service>
    <metadb host='localhost' name='cvcdatadb' user='dbuser' password=''/>
    <computing system="calculator" type="LOCAL" ip="127.0.0.1"/>
<!-- Data segment. Order is not important. -->

    <data uid='Data_1' type='dataset'> <!-- type: dataset, array -->
    	<description title='Collection long name' name='Temperature' units='K'/>
	<dataset name='ERA40' resolution='2.5x2.5' time_step='6h' scenario='-'/>  <!-- ERAINT -->
    	<variable name='2t' tempk2c='no'/> <!-- TMP, air, 2T, TAV, precip-->
	<region units='degrees'>
	    <!-- <point lon=[/LU_LON/] lat=[/LU_LAT/]/> -->
            <point lon='-180' lat='88'/>
            <point lon='180' lat='88'/>
            <point lon='180' lat='-88'/>
            <point lon='-180' lat='-88'/>
    	</region>
	<levels values='2m'/>
	<time uid='Input_1' template='YYYYMMDDHH'>
	    <!-- <segment name='' beginning=[/START_DATE/] ending=[/END_DATE/]/> -->
	    <segment name='Seg1' beginning='1961010100' ending='1961123118'/>
	</time>
    </data>
    
    <destination uid='Image_1' type='image'> <!-- type: 'image', 'raw' -->
	<file name='../output/output.tiff' type='geotiff'/> <!-- if graphics.kind=='shaded', then file.type='eps' OR 'geotiff'; graphics.kind=='vector': file.type='shape'; graphics.kind=='multiline': file.type='eps'; for kind=='tile' : 'geotiff24' -->
	<projection name='cylindrical'> <!-- 'azimuthal equidistant, 'cylindrical',... -->
	    <p0lon units='degrees'>0</p0lon>
	    <p0lat units='degrees'>0</p0lat>
	    <rot units='degrees'>0</rot>
	    <limits units='degrees'>
		<limit role='left'>-180</limit>
		<limit role='right'>180</limit>
		<limit role='top'>90</limit>
		<limit role='bottom'>-90</limit>
	    </limits>
	</projection>
	<graphics title='' kind='shaded'> <!-- kind: 'shaded', 'vector' (replaces 'contour', 'station', and 'vector'); 'tile', 'multiline', 'regress2d' -->
	    <width units='pixels'>3072</width>
	    <height units='pixels'>2304</height>
	    <legend title='Month max of daily max' kind='file' type='continuous' position='none'> <!-- kind: 'embedded', 'file', 'none'; position: 'right', 'left', 'top', 'bottom' (only for kind=='embedded') -->
		<units>K</units> <!-- added after legend's title -->
		<nlabels>11</nlabels> <!-- !!! number of labels in legend -->
		<ncolors>10</ncolors> <!-- number of discrete colors in legend -->
		<limited>no</limited> <!-- fixed legend limits: yes/no -->
		<minimum>-15.0</minimum> <!-- ignored if limited == no -->
		<maximum>15.0</maximum> <!-- ignored if limited == no -->
		<file name='../output/output.sld' type='xml'/> <!-- file for legend (if legend kind=='file'), type: 'tiff', 'png', 'jpeg', 'gif', 'bmp', 'ppm, 'srf'  -->
	    </legend>
	    <colortable>RAINBOW</colortable>  <!-- only for graphics kind=='shaded', e.g.: RAINBOW --> 
	    <colorscale>linear</colorscale> <!-- only for graphics kind=='shaded', linear/log -->
	    <blackbg>no</blackbg> <!-- black background -->
    	    <smoothing>yes</smoothing> <!-- only for graphics kind=='shaded': yes/no -->
	    <steps>30</steps> <!-- only for graphics kind == 'contour' or for file type == 'shape' -->
	</graphics>
    </destination>    

    <destination uid="File_1" type="raw"><!-- uid to be generated, then used in processing -->
      <file name='../output/output.nc' type="netcdf"/> <!--type: 'netcdf', 'geotiff'; 'bin', xml' --><!-- PHP pathname -->
    </destination>
    
    <data uid='Result_1' type='array'>
    	<description title='Month max of daily max' name='Temperature' units='K' source='Data_1'/>
	<time uid='Output_1' template='YYYYMMDDHH'>
	    <!-- <segment name='' beginning=[/START_DATE/] ending=[/END_DATE/]/> -->
	    <segment name='Seg1' beginning='1961010100' ending='1961123118'/>
	</time>
    </data>

    <data uid='ModuleParameters_1' type='parameter'>
    	<param uid='timeMax' type='string'>segment</param> <!-- data, day, segment -->
    </data>

<!-- End of data segment -->

<!-- Code segment. Order is IMPORTANT! -->

    <processing uid='Process_1' class='cvcCalcMaximum' module_path=''>
    	<input uid='P1Input1' data='Data_1'/>
    	<input uid='P1Parameter1' data ='ModuleParameters_1'/>
    	<output uid='P1Output1' data='Result_1'/>
    </processing>
    
    <processing uid='Visualization_1' class='cvcOutput'>
	<input uid='V1Data1' data='Result_1'/>
	<input uid='V1Destination1' data='Image_1'/>
    </processing>

    <processing uid="Output_1" class="cvcOutput">
      <input uid="O1Data1" data="Result_1"/>
      <input uid="O1Destination1" data="File_1"/>
    </processing>
            
<!-- End of code segment -->

</task>

=== garrichello/gcoret/mod/calc/templates/DurColdNights.tmpl.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE task SYSTEM "ctdl.dtd">
<task uid='Task1' owner='Owner1' description='' root_path='/opt/gcoret/' data_module_path=''>
    <service processingClass='' calculationParameter='' trend='' isBaseLayer=''><!-- GUI service params -->
      <timePeriod type=''>
        <dateStart year='' month='' day=''/>
        <dateEnd year='' month='' day=''/>
      </timePeriod>
    </service>
    <metadb host='localhost' name='cvcdatadb' user='dbuser' password=''/>
    <computing system="calculator" type="LOCAL" ip="127.0.0.1"/>
<!-- Data segment. Order is not important. -->

    <data uid='Data_1' type='dataset'> <!-- type: dataset, array -->
    	<description title='ERA Interim 075 reanalysis' name='Temperature' units='K'/>
	<dataset name='ERAInt' resolution='0.75x0.75' time_step='6h' scenario='-'/>  <!-- ERAINT -->
    	<variable name='t2m' tempk2c='yes'/> <!-- TMP, air, 2T, TAV, precip-->
	<region units='degrees'>
	    <point lon='55' lat='75'/> 
	    <point lon='130' lat='75'/>
	    <point lon='130' lat='50'/>
	    <point lon='55' lat='50'/>
	</region>
	<levels values='2m'/>
	<time uid='Input_1' template='YYYYMMDDHH'>
	    <segment name='Seg1' beginning='1991010100' ending='1991123118'/>
	    <segment name='Seg1' beginning='1992010100' ending='1992123118'/>
	    <segment name='Seg1' beginning='1993010100' ending='1993123118'/>
	</time>
    </data>
    
    <data uid='Data_2' type='dataset'> <!-- type: dataset, array -->
    	<description title='ERA40 Reanalysis' name='Temperature' units='K'/>
	<dataset name='ERA40' resolution='2.5x2.5' time_step='6h' scenario='-'/>  <!-- ERAINT -->
    	<variable name='2t' tempk2c='yes'/> <!-- TMP, air, 2T, TAV, precip-->
	<region units='degrees' lon0='0'>
	    <point lon='55' lat='75'/>
	    <point lon='130' lat='75'/>
	    <point lon='130' lat='50'/>
	    <point lon='55' lat='50'/>
	</region>
	<levels values='2m'/>
	<time uid='Input_2' template='YYYYMMDDHH'>
	    <segment name='Seg1' beginning='1960123000' ending='1962010218'/>
            <segment name='Seg2' beginning='1961123000' ending='1963010218'/>
	    <segment name='Seg3' beginning='1962123000' ending='1964010218'/>
	    <segment name='Seg4' beginning='1963123000' ending='1965010218'/>
	    <segment name='Seg5' beginning='1964123000' ending='1966010218'/>
	    <segment name='Seg6' beginning='1965123000' ending='1967010218'/>
            <segment name='Seg7' beginning='1966123000' ending='1968010218'/>
	    <segment name='Seg8' beginning='1967123000' ending='1969010218'/>
	    <segment name='Seg9' beginning='1968123000' ending='1970010218'/>
	    <segment name='Seg10' beginning='1969123000' ending='1971010218'/>
	</time>
    </data>

    <destination uid='Image_1' type='image'> <!-- type: 'image', 'raw' -->
	<file name='ColdNights_dur_eraint.tiff' type='geotiff'/> <!-- type for graphics kind='shape': 'eps', 'geotiff'; kind='contour'/'station': 'eps', 'shape'; for kind=='multiline': 'eps'; for kind=='tile' : 'geotiff24' -->
	<projection name='cylindrical'> <!-- 'azimuthal equidistant, 'cylindrical',... -->
	    <limits units='degrees'>
          	<limit role="left">-180</limit>
	        <limit role="right">180</limit>
          	<limit role="top">90</limit>
          	<limit role="bottom">-90</limit>                                        
	    </limits>
	</projection>
	<graphics title='Cold Nights Duration' kind='shaded'> <!-- kind: 'shaded', 'contour', 'station', 'tile'; 'multiline', 'vector', 'regress2d' -->
	    <width units='pixels'>3072</width>
	    <height units='pixels'>2304</height>
	    <legend title='Duration' kind='file' type='continuous' position='none'> <!-- kind: 'embedded', 'file', 'none'; position: 'right', 'left', 'top', 'bottom' (only for kind=='embedded') -->
		<units>corTM</units> <!-- added after legend's title -->
		<nlabels>11</nlabels> <!-- !!! number of labels in legend -->
		<ncolors>10</ncolors> <!-- number of discrete colors in legend -->		
		<limited>no</limited> <!-- fixed legend limits: yes/no -->
		<minimum>-15.0</minimum> <!-- ignored if limited == no -->
		<maximum>15.0</maximum> <!-- ignored if limited == no -->
		<file name='ColdNights_dur_eraint.sld' type='xml'/> <!-- file for legend (if legend kind=='file'), type: 'tiff', 'png', 'jpeg', 'gif', 'bmp', 'ppm, 'srf'  -->
	    </legend>
	    <colortable>RAINBOW</colortable>  <!-- only for graphics kind=='shaded' -->
	    <colorscale>linear</colorscale> <!-- only for graphics kind=='shaded' -->
	    <smoothing>yes</smoothing> <!-- only for graphics kind=='shaded' -->
	</graphics>
    </destination>

    <destination uid='File_1' type='raw'>
		<file name='ColdNights_dur_eraint.nc' type='netcdf'/> <!--type: 'netcdf', 'geotiff'; 'bin', xml' -->
    </destination>   

    <data uid='Result_1' type='array'>
    	<description title='Time averaged data' name='Temperature' units='C' source='Data_1'/>
	<time uid='Input_1' template='YYYYMMDDHH' step='1y'>
	    <segment name='Seg1' beginning='1991010100' ending='1991123118'/>
	    <segment name='Seg1' beginning='1992010100' ending='1992123118'/>
	    <segment name='Seg1' beginning='1993010100' ending='1993123118'/>
	</time>
    </data>

    <data uid='Result_2' type='array'>
    	<description title='Time averaged data' name='Temperature' units='C' source='Data_2'/>
	<time uid='Input_2' template='YYYYMMDDHH' step='6h'>
	    <segment name='Seg1' beginning='1960123000' ending='1962010218'/>
            <segment name='Seg1' beginning='1961123000' ending='1963010218'/>
            <segment name='Seg1' beginning='1962123000' ending='1964010218'/>
            <segment name='Seg1' beginning='1963123000' ending='1965010218'/>
            <segment name='Seg1' beginning='1964123000' ending='1966010218'/>
            <segment name='Seg1' beginning='1965123000' ending='1967010218'/>
            <segment name='Seg1' beginning='1966123000' ending='1968010218'/>
            <segment name='Seg1' beginning='1967123000' ending='1969010218'/>
            <segment name='Seg1' beginning='1968123000' ending='1970010218'/>
            <segment name='Seg1' beginning='1969123000' ending='1971010218'/>
	</time>
    </data>

    <data uid='Result_3' type='array'>
    	<description title='Time averaged data' name='Temperature' units='C' source='Data_2'/>
	<time uid='Output_2' template='YYYYMMDDHH' step='1y'>
	    <segment name='Seg1' beginning='1961010100' ending='1971123118'/>
	</time>
    </data>

    <data uid='Result_4' type='array'>
    	<description title='Duration of cold nights' name='Duration' units='days'/>
	<time uid='Output_1' template='YYYYMMDDHH' step='1y'>
	    <segment name='Seg1' beginning='1991010100' ending='1993123118'/>
	</time>
    </data>

    <data uid='ModuleParameters_1' type='parameter'>
    	<param uid='timeMin' type='string'>day</param> <!-- data, day, segment, mean -->
        <param uid='percentileThreshold' type='integer'>10</param> <!-- for instance, 5, 10, 25, 95 -->
    	<param uid='exceedanceType' type='string'>duration</param> <!-- frequency, intensity, duration -->
    </data>
    
<!-- End of data segment -->

<!-- Code segment. Order is IMPORTANT! -->

    <processing uid='Process_1' class='cvcCalcMinimum' module_path=''>
    	<input uid='P1Input1' data='Data_1'/>
    	<input uid='P1Parameter' data ='ModuleParameters_1'/>
    	<output uid='P1Output1' data='Result_1'/>
    </processing>

    <processing uid='Process_2' class='cvcCalcMinimum' module_path=''>
    	<input uid='P2Input1' data='Data_2'/>
    	<input uid='P2Parameter' data ='ModuleParameters_1'/>
    	<output uid='P2Output1' data='Result_2'/>
    </processing>

    <processing uid='Process_3' class='cvcCalcLowPDFtail' module_path=''>
    	<input uid='P3Input1' data='Result_2'/>
    	<input uid='P3Parameter' data ='ModuleParameters_1'/>
    	<output uid='P3Output1' data='Result_3'/>
    </processing>

    <processing uid='Process_4' class='cvcCalcLowExceed' module_path=''>
    	<input uid='P4Input1' data='Result_1'/>
    	<input uid='P4Input2' data='Result_3'/>
    	<input uid='P4Parameter' data ='ModuleParameters_1'/>
    	<output uid='P4Output1' data='Result_4'/>
    </processing>
    
    <processing uid='Visualization_1' class='cvcOutput'>
	<input uid='V1Input1' data='Result_4'/>
	<input uid='V1Destination' data='Image_1'/>
    </processing>

    <processing uid="Output_1" class="cvcOutput">
	<input uid="O1Data1" data="Result_4"/>
        <input uid="O1Destination" data="File_1"/>
    </processing>


<!-- End of code segment -->

</task>
